services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somepassword
      POSTGRES_DB: postgres
    user: postgres
    volumes:
      - pgdata:/var/lib/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 5s
      timeout: 5s
      retries: 5

  weaviate:
    image: semitechnologies/weaviate:latest
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai,multi2vec-clip"
      CLUSTER_HOSTNAME: "node1"
      CLIP_INFERENCE_API: http://multi2vec-clip:8080  # Set the inference API endpoint
  multi2vec-clip:  # Set the name of the inference container
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:openai-clip-vit-base-patch16
    environment:
      ENABLE_CUDA: 0  # Set to 1 to enable

volumes:
  pgdata:
