# Generated by Django 5.1.6 on 2025-03-05 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="名前"),
                ),
            ],
            options={
                "verbose_name": "タグ",
                "verbose_name_plural": "タグ",
            },
        ),
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "content",
                    models.CharField(blank=True, default="", max_length=10000, verbose_name="内容"),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="日付")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "日記",
                "verbose_name_plural": "日記",
            },
        ),
        migrations.CreateModel(
            name="DiaryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="image/diary_image", verbose_name="写真"
                    ),
                ),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_images",
                        to="api.diary",
                        verbose_name="日記",
                    ),
                ),
            ],
            options={
                "verbose_name": "日記写真",
                "verbose_name_plural": "日記写真",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=10000, verbose_name="タイトル"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "セクション",
                "verbose_name_plural": "セクション",
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "User"), (1, "AI")], default=0, verbose_name="ロール"
                    ),
                ),
                (
                    "content",
                    models.CharField(blank=True, default="", max_length=10000, verbose_name="内容"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat",
                        to="api.section",
                        verbose_name="セクション",
                    ),
                ),
            ],
            options={
                "verbose_name": "セクション",
                "verbose_name_plural": "セクション",
            },
        ),
        migrations.CreateModel(
            name="DiaryTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_tags",
                        to="api.diary",
                        verbose_name="日記",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_tags",
                        to="api.tag",
                        verbose_name="タグ",
                    ),
                ),
            ],
            options={
                "verbose_name": "日記タグ",
                "verbose_name_plural": "日記タグ",
            },
        ),
        migrations.AddConstraint(
            model_name="diary",
            constraint=models.UniqueConstraint(fields=("date", "user"), name="one_user_per_date"),
        ),
    ]
