# Generated by Django 5.1.6 on 2025-03-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_chat_options_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="タイトル"),
        ),
    ]
