# Generated by Django 5.1.6 on 2025-03-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_diary_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="role",
            field=models.IntegerField(
                choices=[(0, "User"), (1, "AI")], default=0, verbose_name="ロール"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="タイトル"),
        ),
    ]
