# Generated by Django 5.1.6 on 2025-03-09 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_schedule_role_schedule_title"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="diary",
            name="one_user_per_date",
        ),
    ]
