# Generated by Django 5.1.6 on 2025-03-14 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_diary_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="suggest_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
